# Use the official Node.js 14 image as the base
FROM node:19.0.0

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and yarn.lock
COPY package.json yarn.lock ./

# Install dependencies using Yarn
RUN yarn install

# Copy the rest of the app files
COPY . .

# Build the Nuxt app
RUN yarn build

# Expose the desired port (e.g., 3000)
EXPOSE 3000

# Start the Nuxt app
CMD [ "yarn", "start" ]
