version: "3"
services:
  database:
    image: postgres:latest
    container_name: "ObsDatabase"
    restart: always
    env_file:
      - .env  
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ./obs-database/data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
