version: "3"
services:
  database:
    image: postgres:latest
    container_name: "ObsDatabase"
    restart: always
    env_file:
      - .env
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ./obs-database/data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./services/backend # Specify the path to your backend Dockerfile
    container_name: "ObsBackend"
    restart: always
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:9191"
    volumes:
      - ./upload:/usr/src/app/upload
    depends_on:
      - database

  nginx:
    image: nginx:latest
    container_name: "ObsCDN"
    restart: always
    env_file:
      - .env
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./upload:/upload # Mount the uploads directory from the backend service
    depends_on:
      - backend

volumes:
  uploads:
