# Use a Rust base image
FROM rust:latest as builder
# Create a final lightweight image
FROM debian:bullseye-slim

COPY --from=ubi /usr/lib64/libgcc_s.so.1 /usr/lib64/libgcc_s.so.1
COPY --from=ubi /usr/lib64/libstdc++.so.6 /usr/lib64/libstdc++.so.6
COPY --from=ubi /usr/lib64/libz.so.1 /usr/lib64/libz.so.1


# Set working directory
WORKDIR /usr/src/app

# Copy the source code
COPY . .

# Install required dependencies
RUN apt-get update && apt-get install -y libc6

# Build the application
RUN cargo build --release




# Copy the built executable from the builder stage
COPY --from=builder /usr/src/app/target/release/obs-overlay-backend /usr/local/bin/

# Set the entrypoint for running the binary
CMD ["obs-overlay-backend"]
